apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: mo991207/counter-springboot-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-backend-config
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: demo-backend-config
                  key: db_username
            - name: DB_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-backend-config
                  key: db_driver_class_name
