# Deployment 패치
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: demo-frontend
          env:
            - name: ENVIRONMENT
              value: "development"  # Set environment-specific variables
          resources:
            limits:
              memory: "256Mi"  # Limit the resources for development
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

# Service 패치
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: demo-frontend
  type: ClusterIP  # Change service type to ClusterIP for development
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

