apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "fb74-211-244-225-211.ngrok-free.app"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: demo-backend
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-frontend
            port:
              number: 3000
