apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: 2827c33330d5fca05afd508be3ef0674dc6935f2
- name: mo991207/counter-react-app
  newName: mo991207/counter-react-app
  newTag: 2827c33330d5fca05afd508be3ef0674dc6935f2

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

