apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: fc5b9753fe580ea31d5b166cc0724b2a7c2a8b9f
- name: mo991207/counter-react-app
  newName: yoonjini/ktb_front
  newTag: fc5b9753fe580ea31d5b166cc0724b2a7c2a8b9f

resources:
  - ../../base
  - nginx/ingress-controller.yml
  - nginx/ingress-class.yml
  - nginx/ingress.yml

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

