apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: 455019ca839fd402cc5416737fde8b49e9fb9a36
- name: mo991207/counter-react-app
  newName: mo991207/counter-react-app
  newTag: 455019ca839fd402cc5416737fde8b49e9fb9a36

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

