apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: a1c511e0300475d2fae2c77224f68064684ce05f
- name: mo991207/counter-react-app
  newName: mo991207/counter-react-app
  newTag: a1c511e0300475d2fae2c77224f68064684ce05f

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

