apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: f702ee0b33419374d9d5e1c5f106fc0b3293b7eb
- name: mo991207/counter-react-app
  newName: yoonjini/ktb_front
  newTag: f702ee0b33419374d9d5e1c5f106fc0b3293b7eb

resources:
  - ../../base
  - nginx/ingress-controller.yml
  - nginx/ingress-class.yml
  - nginx/ingress.yml

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

