apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: 0ff58e40cbcad68a23976d3130082077b999559c
- name: mo991207/counter-react-app
  newName: yoonjini/ktb_front
  newTag: 0ff58e40cbcad68a23976d3130082077b999559c

resources:
  - ../../base
  - nginx/ingress-controller.yml
  - nginx/ingress-class.yml
  - nginx/ingress.yml

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

