apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: 32ba0a1c5d30d7a17ac72a8748b741b8bd071c44
- name: mo991207/counter-react-app
  newName: yoonjini/ktb_front
  newTag: 32ba0a1c5d30d7a17ac72a8748b741b8bd071c44

resources:
  - ../../base
  - nginx/ingress-controller.yml
  - nginx/ingress-class.yml
  - nginx/ingress.yml

patchesStrategicMerge:
  - ingress-patch.yml
  - frontend-patch.yml
  - backend-patch.yml

