apiVersion: v1
kind: Service
metadata:
  name: backend-spring-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: backend-spring-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 #selector app pod의 TCP 8080 포트가 타깃
