# install.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: argocd-notifications
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-notifications-controller
  namespace: argocd-notifications
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller
  namespace: argocd-notifications
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-controller
  namespace: argocd-notifications
subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd-notifications
roleRef:
  kind: Role
  name: argocd-notifications-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-notifications-controller
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "appprojects"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-notifications-controller
roleRef:
  kind: ClusterRole
  name: argocd-notifications-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd-notifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-notifications-controller
  template:
    metadata:
      labels:
        app: argocd-notifications-controller
    spec:
      serviceAccountName: argocd-notifications-controller
      containers:
        - name: controller
          image: argoprojlabs/argocd-notifications:v1.2.1
          args:
            - --argocd-repo-server
            - http://argocd-repo-server.argocd.svc:8081
