# notifications-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  config.yaml: |
    context:
      - name: discord
        type: discord
        url: $DISCORD_WEBHOOK_URL

    triggers:
      - name: on-sync-failed
        condition: app.status.operationState.phase == 'Failed'
        template: sync-failed

    templates:
      - name: sync-failed
        title: Application {{.app.metadata.name}} sync failed
        body: |
          Application {{.app.metadata.name}} has failed to sync.
          Error: {{.app.status.operationState.message}}
          View details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  discord-webhook: "https://discord.com/api/webhooks/1270893799496749107/8Unjsf-Oj-SLv45EP525mQF2a861zflOpjiIrq9mILP4I8TFHnDdR5-YO_U9Fl9Wz7lK"
