apiVersion: v1
kind: Service
metadata:
  name: frontend-react-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: frontend-react-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #selector app pod의 TCP 80 포트가 타깃
