apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-app #Deployment의 레이블 정의
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react-app #실행될 Pod의 레이블 정의
  template:
    metadata:
      labels:
        app: frontend-react-app
    spec:
      containers:
        - name: frontend-react-app
          image: mo991207/counter-react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80 #nginx serving
