apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: mo991207/counter-springboot-app  # 기존 이미지 이름
  newName: mo991207/counter-springboot-app  # 새로운 이미지 이름
  newTag: 455019ca839fd402cc5416737fde8b49e9fb9a36
- name: mo991207/counter-react-app
  newName: mo991207/counter-react-app
  newTag: 455019ca839fd402cc5416737fde8b49e9fb9a36

resources:
  - ../../base
  - clusterrole/cluster-role-alb.yml
  - config/configmap-alb.yml
  - alb/cert-manager.yaml
  - alb/ingress-controller-alb.yml
  - alb/ingress-class.yaml

patches:
  - target:
      kind: Ingress
      name: ingress-alb
      namespace: default
    path: ingress-patch-alb.yml
  - target:
      kind: Deployment
      name: demo-frontend
      namespace: default
    path: frontend-deployment-patch.yml
  - target:
      kind: Service
      name: demo-frontend
      namespace: default
    path: frontend-service-patch.yml
  - target:
      kind: Deployment
      name: demo-backend
      namespace: default
    path: backend-deployment-patch.yml
  - target:
      kind: Service
      name: demo-backend
      namespace: default
    path: backend-service-patch.yml
