apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-cluster
  region: ap-northeast-2

vpc:
  nat:
    gateway: Single

availabilityZones: ["ap-northeast-2a", "ap-northeast-2b"]

nodeGroups:
  - name: web-service-nodes
    instanceType: t2.micro
    desiredCapacity: 1 #overspec 고려
    minSize: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: my-ec2-keypair
    subnets:
      - ap-northeast-2a
    labels:
      role: web-service
    tags:
      nodegroup-role: web-service
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
  - name: back-nodes  # 이름 변경
    instanceType: t2.medium  # 인스턴스 스펙 수정
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks-demo-cluster --kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot'
    privateNetworking: true # Private Subnet에 위치하도록
    ssh:
      allow: true
      publicKeyName: my-ec2-keypair
    subnets:
      - ap-northeast-2a
    labels:
      role: back-end  # 역할 변경
    tags:
      nodegroup-role: back-end  # 태그 변경
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        fsx: true
        certManager: true
        externalDNS: true
  - name: ingress-controller-nodes
    instanceType: t2.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks-demo-cluster --kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot'
    ssh:
      allow: true
      publicKeyName: my-ec2-keypair
    subnets:
      - ap-northeast-2a # Public Subnet
    labels:
      role: ingress-controller
    tags:
      nodegroup-role: ingress-controller
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        albIngress: true # albIngress에 대한 권한 추가

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "scheduler"] # 필요한 로그 타입만 활성화

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest