apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - namespaces
      - endpoints
      - services
      - configmaps
      - events
      - nodes
    verbs:
      - get
      - list
      - watch
      - create 
      - update
      - patch
      - delete
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingressclasses
      - ingresses
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
