apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/frontend-deployment.yml
  - frontend/frontend-service.yml
  - backend/backend-deployment.yml
  - backend/backend-service.yml
  - backend/backend-config.yml
  # - ingress/alb/ingress-controller.yml
  # - ingress/alb/ingress-class.yml
  # - ingress/alb/ingress.yml
  # 여기도 overlays/dev로 옮기기
  # - ingress/nginx/ingress-controller.yml
  # - ingress/nginx/ingress-class.yml
  # - ingress/nginx/ingress.yml
  - clusterrole/cluster-role.yml
  - clusterrole/cluster-role-binding.yml
