apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/frontend-deployment.yml
  - frontend/frontend-service.yml
  - backend/backend-deployment.yml
  - backend/backend-service.yml
  - backend/backend-config.yml
  - ingress/ingress-controller.yml
  - ingress/ingress-class.yml
  - ingress/ingress.yml
  - clusterrole/cluster-role.yml
  - clusterrole/cluster-role-binding.yml


